steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'web', '--trigger-http', '--region', 'asia-southeast2', '--runtime', 'nodejs12', '--entry-point', 'handler']
  dir: 'backend'